server:
  port: ${PORT:8081}
  
spring:
  profiles:
    active: dev
  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/product-db
    username: admin
    password: 123456
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS

  sql:
    init:
      continue-on-error: true
      platform: postgresql
      mode: always

app-config:
  secrets:
    api-secret: ${API_SECRET:YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=}